### ISSUE TITLE
I install it in python3.8, run error

### ISSUE THREAD

**Issue by m986883511** [adevecchi/SimpleSerialWebTerminalPython#3]
```shell
(tmp1) PS Z:\code\tmp\新建文件夹\SimpleSerialWebTerminalPython> python .\server.py
Traceback (most recent call last):
  File ".\server.py", line 70, in <module>
    httpServer.listen(options.port)
  File "C:\Users\one\.conda\envs\tmp1\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\one\.conda\envs\tmp1\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\one\.conda\envs\tmp1\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\one\.conda\envs\tmp1\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\one\.conda\envs\tmp1\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

what the python version is

**Comment by adevecchi** [comment]
This issue is related to tornado version 6.0.4, please update to version 6.3.3

This will work with Python 3.8 and later
